# Generated by Django 5.2.6 on 2025-09-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_nombre_alter_producto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
    ]
