name: Deploy Productly

on:
  push:
    branches:
      - main # Solo se ejecuta cuando haces push a main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona tu repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Inicia sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construye y sube la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: juanpaz98/productly:latest
